# Generated by Buildr 1.4.5, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "http"
COPYRIGHT = ""

HTTP_COMPONENTS = group("httpclient","httpcore",:under => "org.apache.httpcomponents",:version => "4.1")
JSON = 'org.json:json:jar:20090211'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.remote << "http://repo1.maven.org/maven2/"

desc "The Http project"
define "GreenHttp" do
  manifest["Implementation-Vendor"] = COPYRIGHT
  project.version = VERSION_NUMBER
  project.group   = GROUP

  compile.with    transitive(HTTP_COMPONENTS),JSON
  # test.compile.with # Add classpath dependencies
  shell.using     :jirb
  package         :jar
end
